In [2]:
A <- c(1,2,3)
B <- c(4,5,6)
AB <- rbind(A, B)
AB

[,1] [,2] [,3]
A 1    2    3   
B 4    5    6

In [21]:
mat <- matrix(1:9, nrow=3)
mat

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [22]:
#Confirm that mat is a matrix
class(mat) == 'matrix'

[1] TRUE

In [11]:
mat2 <- matrix(1:25, byrow=TRUE, nrow=5)
mat2

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20  
[5,] 21   22   23   24   25

In [12]:
mat2[2:3, 2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

In [10]:
mat2[4:5, 4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

In [13]:
sum(mat2)

[1] 325

In [19]:
matrix(runif(20, min=0, max=100), nrow=4)

[,1]     [,2]     [,3]     [,4]     [,5]     
[1,] 39.92618 96.32147 94.37812 75.89279 74.362955
[2,] 48.78532 87.28291 54.89860 64.69047 25.841025
[3,] 26.37371 99.19057 62.62902 50.73437  3.651687
[4,] 76.22506 86.05152 81.69816 32.35152 81.565830